hermione_account = scb.search_account_from_account_no('0987654321')
debit_card = hermione_account.get_card()
kfc_account = scb.search_account_from_account_no('0000000321')
kfc = scb.search_seller('KFC')
edc = kfc.search_edc_from_no('2101')
print("Test Case #4")
print("Hermione's Debit Card No : ", debit_card.get_card_no())
print("Hermione's Account No : ",hermione_account.get_account_no())
print("Seller : ", kfc.get_name())
print("KFC's Account No : ", kfc_account.get_account_no())
print("KFC account before paid : ",kfc_account.get_amount())
print("Hermione account before paid : ",hermione_account.get_amount())
edc.paid(debit_card, 500, kfc_account)
print("KFC account after paid : ",kfc_account.get_amount())
print("Hermione account after paid : ",hermione_account.get_amount())
print("")